### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by Suntrie** [wizarlock/RussianCheckers#1]
1. Какова дефолтная область видимости переменных? Мотивирован ли такой выбор чем-либо, например, для `   CheckersDesk desk;`?
2. `public static final int rows = 8;` - про стандартное именование констант в Java можно почитать, например, [здесь](https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names)
3. ` public void initDesk() {` - блоки инициализации для чёрных и белых здесь практически повторяются -> выносим приватный вспомогательный метод, аналогично для Game onCheckerAdded/ onCheckerRemoved, логика - общая
4. `public boolean hasChecker(Cell cell) {` - это метод доски или клетки? (с учетом наличия класса Cell, кажется, что последней)
5. Среди классов пакета pieces кажется логичным подумать об установлении отношений наследования. Кроме этого, с учетом того, что в create всех активностей выполняется одна и та же задача по установке флага, можно выделить и базовую активность, реализовав ее onCreate в соответствии с паттерном [Template method](https://refactoring.guru/ru/design-patterns/template-method/java/example);
6. onClick-и можно прописывать [на стороне xml](https://stackoverflow.com/a/4153842), что избавит от boilerplate-кода по поиску и установке обработчиков нажатия в активностях
7. Прокомментируйте, пожалуйста, что даёт вложенность OnCheckerActionListener и класса Checker? Что даёт такое решение? В чем разница между статическим и обычным вложенными классами?

**Comment by wizarlock** [comment]
1) Если никакой модификатор не используется, считается, что используется модификатор по умолчанию. Классы, поля или методы с таким модификатором видны всем классам пакета, в котором они объявлены. Не мотивирован, сделал public.
2) Пофиксил
3) Пофиксил
4) Переделал
5) Теперь ничего нет
6) Сделано
7) Вложенные классы применяются в тех случаях, когда нужно написать небольшой вспомогательный код для другого класса. Вложенный класс создают также, чтобы скрыть его переменные и методы от внешнего мира. Таким образом, вложенный класс еще один элегантный способ ограничения области видимости.

Применение статического вложенного класса означает следующее:
для создания объекта статического вложенного класса не нужен объект внешнего класса
из объекта вложенного класса нельзя обращаться к нестатическим членам внешнего класса

Внутренний класс имеет доступ ко всем переменным и методам своего внешнего класса и может непосредственно ссылаться на них.

По этим критериям и выбрал вложенный класс

**Comment by Suntrie** [comment]
1. Почему public переменные - это плохо, напомните, пожалуйста? Особенно для классов модели в MVC? (и зачем вообще нужно разделение на слои MVC)?
2. ` static final int rows = 8;` -  пока не похоже. Это правда константа, т.е. public static final - это было справедливо. Но имя здесь должно быть другое ROWS (если несколько слов - WORD1_WORD2_WORD3)
3. В коде а) очень много повторений
`cellExist(new Cell(cell.getY() + (coefficient + 1) * entry.getValue().getY(), cell.getX() + (coefficient + 1) * entry.getValue().getX(), null))` - вот это условие, например, считается трижды
`cells.get(cell.getY() + (coefficient + 1) * entry.getValue().getY()).get(cell.getX() + (coefficient + 1) * entry.getValue().getX()).getChecker() == null` - это два раза

```
if (!whoseMove) {
            for (int i = 0; i < rows; i++)
                for (int j = 0; j < columns; j++) {
                    Cell cell = cells.get(i).get(j);
                    if (cell.getChecker() != null)
                        if (cell.getChecker().getColor() == WHITE) return false; // зачем?
                }
        }
```
- ^^^ почему здесь if вынесен из-под цикла, понять сложновато. Если из-за производительности - заведите, пожалуйста, приватный метод. Пока все очень грустно;
б) очень много повторяющихся цепочек вызовов, это, к сожалению, в совокупности с другими факторами, делает его заметно малочитаемым.  Попросите, пожалуйста, кого-нибудь из Ваших коллег интерпретировать строку
`  if (cells.get(cell.getY() + entry.getValue().getY()).get(cell.getX() + entry.getValue().getX()).getChecker().getColor() != cell.getChecker().getColor())` - если не выписывать на бумажку, что там происходит поочередно, понять это нереально. Как исправлять: заводим переменные с говорящими именами под повторяющиеся цепочки вызовов. Говорящие имена это НЕ cells и pairs - их просьба также переименовать. Зачем они конкретно нужны? Что в них конкретно лежит?
4. А в чем смысл (есть ли какой-то) делать ` public static boolean cellExist(Cell cell) {` статическим? Если он оперирует только с полями, собственно, клетки??... 
5. Наследование точно нужно поддержать между Coordinates и Cell (потому что из-за его отсутствия, по сути, у Вас сейчас дублирование кода происходит). ` getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);` всё ещё осталось жить. Его вообще можно вытащить в [манифест](https://stackoverflow.com/a/2868052);
6. \+
7. \+

8. `public static Boolean whoseMove = false; ` - делать все статиками - это плохо, это противоречит концепции ООП. А что, если мы модельку захотим использовать на сервере, для того, чтобы заводить по экземпляру игры для каждого из клиентов? Введенные здесь ограничения являются искусственными, для того, чтобы объявить поле статиком - оно реально должно быть _общее_ для всех объектов;
9. `whoseMove` - программист, который работает с Вами, должен будет запомнить, кто из белых/черных true, кто false?.. (стоит переименовать)
10. Каждый раз вызывать метод для инициализации одной и той же мапы - `private Map<Integer, Coordinates> initCoordinates() {` - это как-то дорого. Как варианты: инициализировать как поле в конструкторе или посмотреть на double brackets initialization (при этом прочитать, какие у него есть минусы и прикинуть, вредят ли они в Вашем случае);
11. ` for (Map.Entry<Cell, Cell> entry : pairs.get(i).entrySet())
                if (entry.getKey().equals(cell)) return true;` - ??? Как осуществляется проверка наличия элемента в Map? Почему так делать плохо?
12. `  public static Cell eatingCell = null;` - как правило, при инициализации null-ом нужно добавлять проверки перед использованием (а добавлять их во все методы - забывают). Здесь лучше использовать Optional.Empty (защита от выстрела в ногу);
13. `import static com.example.checkers.model.CheckersDesk.whoseMove;` - использование глобальных переменных - с точки зрения стиля == [зло](https://stackoverflow.com/questions/484635/are-global-variables-bad).

**Comment by wizarlock** [comment]
1) Не подумал. Для ООП использовать надо private
2) Переделал
3) Вроде все пофиксил
4) Поправил
5) Попытался, не вышло, написал в телегу. Не вижу перспектив при использовании наследования, возможно, что я не так вас понял
6) +
7) +
8) Сделано
9) Сделано
10) Не получилось
11) Сделано
12) Не вижу смысла в этом, так как null везде контролируется, он как бы используется для того, чтобы показать, что нет шашки, которая ест
13) Сделано
